name: Mirror to Codeberg

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  codeberg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'https://codeberg.org/TheWebFormula/lithe.git'
          GIT_USERNAME: 'b-3po'
          GIT_PASSWORD: ${{ secrets.CODEBERG_TOKEN }}
